import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import Providers from "./components/Provider";
import Navbar from "./components/layout/Navbar";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-ubuntu", 
});

export const metadata: Metadata = {
  title: "Espa Unusa",
  description: "Generated by Espa Unusa",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${ubuntu.variable} antialiased`}>
        < Navbar />
        <div className="p-5"></div>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
